import { useMemo, useState } from "react";
import type { IntroSuggestion, ProjectManifest } from "../../shared/domain";
import { formatDuration } from "../format";

interface Props { project: ProjectManifest; onProjectUpdated(project: ProjectManifest): void; onClose(): void; }

export function ShortsStudio({ project, onClose }: Props) {
  const [segments, setSegments] = useState<IntroSuggestion[]>(() => structuredClone(project.introSegments));
  const [limit, setLimit] = useState<60 | 180>(60); const [includeBgm, setIncludeBgm] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>(); const [result, setResult] = useState<{ jobId: string; outputPath: string; sizeBytes: number }>();
  const assets = useMemo(() => new Map(project.sources.map((asset) => [asset.id, asset])), [project.sources]);
  const durationMs = segments.reduce((sum, item) => sum + item.outMs - item.inMs, 0);
  const move = (index: number, delta: number) => { const next = [...segments]; const target = index + delta; if (target < 0 || target >= next.length) return; [next[index], next[target]] = [next[target], next[index]]; setSegments(next); };
  const start = async () => {
    setBusy(true); setError(undefined); setResult(undefined);
    try {
      const output = await window.sourceApp.prepareConcatOutput(`SceneryWalker_Shorts_${limit}s.mp4`);
      const completed = await window.sourceApp.startConcatRender({ outputToken: output.token, orderedAssetIds: segments.map((item) => item.assetId), clipSelections: segments.map((item) => ({ assetId: item.assetId, inMs: item.inMs, outMs: item.outMs })), transitionSeconds: 0.3, resolution: "480P", purpose: "SHORTS", shortsSource: "INTRO", shortsPortrait: true, shortsMaxDurationSec: limit, prependIntro: false, includeBgm, subtitleBurnIn: { enabled: false, tracks: [] } });
      setResult(completed);
    } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); }
  };
  return <div className="modal-backdrop" role="presentation"><section className="editor-modal shorts-modal" role="dialog" aria-modal="true" aria-label="製作 Shorts"><header className="modal-header"><div><span className="eyebrow">SHORTS · INTRO SEGMENTS</span><h2>製作 Shorts</h2><p>只複製目前已確認片頭片段的選擇與順序，不改動原本 Intro。直式輸出保留比例，橫式素材使用同源模糊背景。</p></div><button className="icon-button" onClick={onClose} aria-label="關閉">×</button></header><div className="shorts-body"><div className="shorts-options"><label>長度上限<select value={limit} onChange={(e) => setLimit(Number(e.target.value) as 60 | 180)}><option value={60}>60 秒（專案預設）</option><option value={180}>180 秒（明確選擇）</option></select></label><label><input type="checkbox" checked={includeBgm} onChange={(e) => setIncludeBgm(e.target.checked)} /> 套用目前配樂／音量設定</label><span className={durationMs > limit * 1000 ? "inline-warning" : "inline-notice"}>目前選定 {formatDuration(durationMs)}／{limit} 秒</span></div>{segments.length ? <div className="shorts-segment-list">{segments.map((segment, index) => { const asset = assets.get(segment.assetId); return <article key={segment.id}><div><strong>{index + 1}. {asset?.fileName ?? segment.fileName}</strong><span>{formatDuration(segment.outMs - segment.inMs)} · {formatDuration(segment.inMs)}–{formatDuration(segment.outMs)}</span></div><button onClick={() => move(index, -1)} disabled={index === 0}>↑</button><button onClick={() => move(index, 1)} disabled={index === segments.length - 1}>↓</button><button className="danger-text" onClick={() => setSegments((current) => current.filter((item) => item.id !== segment.id))}>排除</button></article>; })}</div> : <div className="empty-state"><h3>尚無已確認片頭片段</h3><p>請先到片頭頁確認片段。</p></div>}{error && <p className="inline-error" role="alert">{error}</p>}{result && <div className="concat-complete"><h3>Shorts 預覽已完成</h3><p>{result.outputPath}</p><button className="secondary-button" onClick={() => void window.sourceApp.playConcatOutput(result.jobId)}>▶ 播放</button><button className="secondary-button" onClick={() => void window.sourceApp.revealConcatOutput(result.jobId)}>在檔案總管顯示</button></div>}<div className="concat-footer-actions"><button className="primary-button" disabled={busy || !segments.length || durationMs > limit * 1000} onClick={() => void start()}>{busy ? "產出中…" : "產出 Shorts 1080×1920"}</button><button className="secondary-button" onClick={onClose}>完成</button></div></div><footer className="settings-footer"><small>Shorts 使用 purpose=SHORTS 並進入共用輸出歷史；本版不自動上傳、不改寫來源。</small></footer></section></div>;
}
