import { contextBridge, ipcRenderer } from "electron";
import type {
  AppApi,
  AiAccountSaveInput,
  AiAnalysisProgress,
  BackgroundJobSnapshot,
  ProjectChangedEvent,
  AiStoryContext,
  AiSubtitleGenerationOptions,
  ConcatRenderProgress,
  ConcatRenderRequest,
  ExternalMediaTarget,
  ExternalPlayerId,
  ExternalPlayerSettingsUpdate,
  BgmTrack,
  MusicSuggestionRequest,
  BrowserUploadPlatform,
  IntroSuggestion,
  MainExclusionRange,
  ZoomSegment,
  PlacementRequest,
  ProjectColorSettings,
  SubtitleCue,
  SubtitleTimelineScope,
  VolumeSegment,
  ImportProgress,
  IntroAnalysisProgress,
  PreviewVariant,
  SortMode,
  YoutubeSettingsUpdate,
  YoutubeUploadProgress,
  YoutubeUploadRequest,
  UserPreferencesUpdate,
  TranslationSettingsUpdate,
  VoiceInputRequest,
} from "../shared/domain";

const api: AppApi = {
  getAppInfo: () => ipcRenderer.invoke("app:get-info"),
  confirmAppClose: () => ipcRenderer.send("app:confirm-close"),
  onAppCloseRequested: (callback: () => void) => {
    ipcRenderer.on("app:close-requested", () => callback());
  },
  clearAppCloseRequestedListeners: () => ipcRenderer.removeAllListeners("app:close-requested"),
  getUserPreferences: () => ipcRenderer.invoke("preferences:get"),
  getBackgroundJobs: () => ipcRenderer.invoke("background:get-jobs"),
  onBackgroundJobs: (callback: (jobs: BackgroundJobSnapshot[]) => void) => { ipcRenderer.on("background:jobs", (_event, jobs: BackgroundJobSnapshot[]) => callback(jobs)); },
  clearBackgroundJobsListeners: () => ipcRenderer.removeAllListeners("background:jobs"),
  onProjectChanged: (callback: (event: ProjectChangedEvent) => void) => { ipcRenderer.on("project:changed", (_event, change: ProjectChangedEvent) => callback(change)); },
  clearProjectChangedListeners: () => ipcRenderer.removeAllListeners("project:changed"),
  updateUserPreferences: (update: UserPreferencesUpdate) => ipcRenderer.invoke("preferences:update", update),
  getProject: () => ipcRenderer.invoke("project:get"),
  getProjectHistoryState: () => ipcRenderer.invoke("project:history-state"),
  undoProject: () => ipcRenderer.invoke("project:undo"),
  redoProject: () => ipcRenderer.invoke("project:redo"),
  chooseFiles: () => ipcRenderer.invoke("source:choose-files"),
  chooseFolder: () => ipcRenderer.invoke("source:choose-folder"),
  chooseIntroFiles: () => ipcRenderer.invoke("intro:choose-files"),
  cancelImport: () => ipcRenderer.invoke("source:cancel-import"),
  getProjectFileState: () => ipcRenderer.invoke("project:get-file-state"),
  saveProject: () => ipcRenderer.invoke("project:save"),
  saveProjectAs: () => ipcRenderer.invoke("project:save-as"),
  openProject: () => ipcRenderer.invoke("project:open"),
  removeMainAsset: (assetId: string) => ipcRenderer.invoke("main:remove-asset", assetId),
  restoreMainAsset: (assetId: string) => ipcRenderer.invoke("main:restore-asset", assetId),
  setIntroSegments: (segments: IntroSuggestion[]) => ipcRenderer.invoke("intro:set-segments", segments),
  setIntroTargetDuration: (durationMs: number) => ipcRenderer.invoke("intro:set-target-duration", durationMs),
  setIntroSegmentMaxDuration: (durationMs: number) => ipcRenderer.invoke("intro:set-segment-max-duration", durationMs),
  setProjectColorSettings: (settings: ProjectColorSettings) => ipcRenderer.invoke("project:set-color-settings", settings),
  removeIntroSegment: (segmentId: string) => ipcRenderer.invoke("intro:remove-segment", segmentId),
  restoreIntroSegment: (segmentId: string) => ipcRenderer.invoke("intro:restore-segment", segmentId),
  setPreviewRange: (assetId, range) => ipcRenderer.invoke("source:set-preview-range", assetId, range.inMs, range.outMs),
  setImageDuration: (assetId: string, durationMs: number) => ipcRenderer.invoke("source:set-image-duration", assetId, durationMs),
  setPhotoSoundEnabled: (assetId: string, enabled: boolean) => ipcRenderer.invoke("source:set-photo-sound", assetId, enabled),
  addMediaInsertion: (anchorVideoAssetId, insertedAssetId, atMs, sourceRange) => ipcRenderer.invoke("main:add-media-insertion", anchorVideoAssetId, insertedAssetId, atMs, sourceRange),
  updateMediaInsertion: (insertionId, atMs, sourceRange) => ipcRenderer.invoke("main:update-media-insertion", insertionId, atMs, sourceRange),
  removeMediaInsertion: (insertionId) => ipcRenderer.invoke("main:remove-media-insertion", insertionId),
  moveMediaInsertion: (insertionId, toIndex) => ipcRenderer.invoke("main:move-media-insertion", insertionId, toIndex),
  setVolumeSegments: (assetId: string, segments: VolumeSegment[]) => ipcRenderer.invoke("source:set-volume-segments", assetId, segments),
  setMainExclusionRanges: (assetId: string, ranges: MainExclusionRange[]) => ipcRenderer.invoke("main:set-exclusion-ranges", assetId, ranges),
  setZoomSegments: (assetId: string, segments: ZoomSegment[]) => ipcRenderer.invoke("main:set-zoom-segments", assetId, segments),
  placeAsset: (assetId: string, placement: PlacementRequest) => ipcRenderer.invoke("project:place-asset", assetId, placement),
  moveTimelineAsset: (assetId: string, toIndex: number) => ipcRenderer.invoke("project:move-asset", assetId, toIndex),
  setSortMode: (sortMode: SortMode) => ipcRenderer.invoke("project:set-sort", sortMode),
  ensureMetadata: (assetId: string) => ipcRenderer.invoke("source:metadata", assetId),
  ensurePreview: (assetId: string, variant: PreviewVariant) =>
    ipcRenderer.invoke("preview:ensure", assetId, variant),
  ensureClipPreview: (assetId: string, inMs: number, outMs: number) =>
    ipcRenderer.invoke("preview:ensure-clip", assetId, inMs, outMs),
  cancelPreview: (assetId: string, variant: PreviewVariant) =>
    ipcRenderer.invoke("preview:cancel", assetId, variant),
  cancelClipPreview: (assetId: string, inMs: number, outMs: number) =>
    ipcRenderer.invoke("preview:cancel-clip", assetId, inMs, outMs),
  chooseConcatOutput: (suggestedName: string) => ipcRenderer.invoke("concat:choose-output", suggestedName),
  prepareConcatOutput: (suggestedName: string) => ipcRenderer.invoke("concat:prepare-output", suggestedName),
  startConcatRender: (request: ConcatRenderRequest) => ipcRenderer.invoke("concat:start", request),
  cancelConcatRender: () => ipcRenderer.invoke("concat:cancel"),
  revealConcatOutput: (jobId: string) => ipcRenderer.invoke("concat:reveal", jobId),
  playConcatOutput: (jobId: string) => ipcRenderer.invoke("concat:play", jobId),
  copyPreviewOutputPath: (jobId: string) => ipcRenderer.invoke("output-history:copy-path", jobId),
  getPreviewOutputHistory: () => ipcRenderer.invoke("output-history:get"),
  chooseExistingPreviewOutputs: () => ipcRenderer.invoke("output-history:choose-existing"),
  removePreviewOutputRecord: (jobId: string) => ipcRenderer.invoke("output-history:remove-record", jobId),
  analyzeIntro: (assetIds: string[], maxDurationMs: number, maxSegmentDurationMs: number) => ipcRenderer.invoke("intro:analyze", assetIds, maxDurationMs, maxSegmentDurationMs),
  cancelIntroAnalysis: () => ipcRenderer.invoke("intro:cancel-analysis"),
  getAiSettings: () => ipcRenderer.invoke("ai:get-settings"),
  saveAiAccount: (input: AiAccountSaveInput) => ipcRenderer.invoke("ai:save-account", input),
  setActiveAiAccount: (accountId: string) => ipcRenderer.invoke("ai:set-active-account", accountId),
  removeAiAccount: (accountId: string) => ipcRenderer.invoke("ai:remove-account", accountId),
  testAiAccount: (accountId: string) => ipcRenderer.invoke("ai:test-account", accountId),
  getTranslationSettings: () => ipcRenderer.invoke("translation:get-settings"),
  updateTranslationSettings: (update: TranslationSettingsUpdate) => ipcRenderer.invoke("translation:update-settings", update),
  testGoogleTranslation: () => ipcRenderer.invoke("translation:test-google"),
  transcribeVoiceInput: (request: VoiceInputRequest) => ipcRenderer.invoke("ai:transcribe-voice-input", request),
  setAiStoryContext: (context: AiStoryContext) => ipcRenderer.invoke("project:set-ai-story-context", context),
  generateAiSubtitles: (options: AiSubtitleGenerationOptions) => ipcRenderer.invoke("subtitle:ai-generate", options),
  buildSubtitleIntroPreview: (includeBgm = false) => ipcRenderer.invoke("subtitle:build-intro-preview", includeBgm),
  cancelSubtitleIntroPreview: () => ipcRenderer.invoke("subtitle:cancel-intro-preview"),
  cancelAiSubtitles: () => ipcRenderer.invoke("subtitle:ai-cancel"),
  getExternalPlayerSettings: () => ipcRenderer.invoke("external-player:get-settings"),
  updateExternalPlayerSettings: (update: ExternalPlayerSettingsUpdate) =>
    ipcRenderer.invoke("external-player:update-settings", update),
  chooseCustomPlayer: () => ipcRenderer.invoke("external-player:choose-custom"),
  removeCustomPlayer: (playerId: ExternalPlayerId) => ipcRenderer.invoke("external-player:remove-custom", playerId),
  openExternalMedia: (assetId: string, target: ExternalMediaTarget) =>
    ipcRenderer.invoke("external-player:open", assetId, target),
  chooseBgmFiles: () => ipcRenderer.invoke("bgm:choose-files"),
  addBgmYoutubeReferences: (urls: string[]) => ipcRenderer.invoke("bgm:add-youtube-references", urls),
  resolveBgmReference: (trackId: string, rightsConfirmed: boolean) => ipcRenderer.invoke("bgm:resolve-reference", trackId, rightsConfirmed),
  sequenceBgmTracks: () => ipcRenderer.invoke("bgm:sequence"),
  setSourceAudioVolume: (volumePercent: number) => ipcRenderer.invoke("project:set-source-audio-volume", volumePercent),
  updateBgmTrack: (track: BgmTrack) => ipcRenderer.invoke("bgm:update", track),
  removeBgmTrack: (trackId: string) => ipcRenderer.invoke("bgm:remove", trackId),
  moveBgmTrack: (trackId: string, toIndex: number) => ipcRenderer.invoke("bgm:move", trackId, toIndex),
  playBgmTrack: (trackId: string) => ipcRenderer.invoke("bgm:play", trackId),
  revealBgmTrack: (trackId: string) => ipcRenderer.invoke("bgm:reveal", trackId),
  copyBgmTrackPath: (trackId: string) => ipcRenderer.invoke("bgm:copy-path", trackId),
  openYoutubeAudioLibrary: () => ipcRenderer.invoke("bgm:open-youtube-audio-library"),
  generateMusicSuggestions: (request: MusicSuggestionRequest) => ipcRenderer.invoke("bgm:ai-suggest", request),
  cancelMusicSuggestions: () => ipcRenderer.invoke("bgm:ai-suggest-cancel"),
  openMusicSuggestion: (url: string) => ipcRenderer.invoke("bgm:open-suggestion", url),
  setSubtitleCues: (cues: SubtitleCue[]) => ipcRenderer.invoke("subtitle:set-cues", cues),
  chooseSubtitleInput: () => ipcRenderer.invoke("subtitle:choose-input"),
  chooseSubtitleOutput: (suggestedName: string) => ipcRenderer.invoke("subtitle:choose-output", suggestedName),
  exportSubtitles: (outputToken: string, scopes?: SubtitleTimelineScope[]) => ipcRenderer.invoke("subtitle:export", outputToken, scopes),
  cancelSubtitleExport: () => ipcRenderer.invoke("subtitle:cancel-export"),
  getYoutubeSettings: () => ipcRenderer.invoke("youtube:get-settings"),
  updateYoutubeSettings: (update: YoutubeSettingsUpdate) => ipcRenderer.invoke("youtube:update-settings", update),
  chooseYoutubeOAuthClient: () => ipcRenderer.invoke("youtube:choose-oauth-client"),
  connectYoutube: () => ipcRenderer.invoke("youtube:connect"),
  cancelYoutubeConnect: () => ipcRenderer.invoke("youtube:cancel-connect"),
  disconnectYoutube: () => ipcRenderer.invoke("youtube:disconnect"),
  uploadYoutubeVideo: (request: YoutubeUploadRequest) => ipcRenderer.invoke("youtube:upload", request),
  cancelYoutubeUpload: () => ipcRenderer.invoke("youtube:cancel-upload"),
  openYoutubeVideo: (videoId: string) => ipcRenderer.invoke("youtube:open-video", videoId),
  openPlatformUpload: (jobId: string, platform: BrowserUploadPlatform) => ipcRenderer.invoke("platform-upload:open", jobId, platform),
  openPlatformPortal: (platform: BrowserUploadPlatform) => ipcRenderer.invoke("platform-upload:open-portal", platform),
  onImportProgress: (callback: (progress: ImportProgress) => void) => {
    ipcRenderer.on("import:progress", (_event, progress: ImportProgress) => callback(progress));
  },
  clearImportProgressListeners: () => ipcRenderer.removeAllListeners("import:progress"),
  onConcatProgress: (callback: (progress: ConcatRenderProgress) => void) => {
    ipcRenderer.on("concat:progress", (_event, progress: ConcatRenderProgress) => callback(progress));
  },
  clearConcatProgressListeners: () => ipcRenderer.removeAllListeners("concat:progress"),
  onIntroAnalysisProgress: (callback: (progress: IntroAnalysisProgress) => void) => {
    ipcRenderer.on("intro:analysis-progress", (_event, progress: IntroAnalysisProgress) => callback(progress));
  },
  clearIntroAnalysisProgressListeners: () => ipcRenderer.removeAllListeners("intro:analysis-progress"),
  onAiAnalysisProgress: (callback: (progress: AiAnalysisProgress) => void) => {
    ipcRenderer.on("ai:analysis-progress", (_event, progress: AiAnalysisProgress) => callback(progress));
  },
  clearAiAnalysisProgressListeners: () => ipcRenderer.removeAllListeners("ai:analysis-progress"),
  onSubtitlePreviewProgress: (callback: (progress: ConcatRenderProgress) => void) => {
    ipcRenderer.on("subtitle:preview-progress", (_event, progress: ConcatRenderProgress) => callback(progress));
  },
  clearSubtitlePreviewProgressListeners: () => ipcRenderer.removeAllListeners("subtitle:preview-progress"),
  onYoutubeUploadProgress: (callback: (progress: YoutubeUploadProgress) => void) => {
    ipcRenderer.on("youtube:upload-progress", (_event, progress: YoutubeUploadProgress) => callback(progress));
  },
  clearYoutubeUploadProgressListeners: () => ipcRenderer.removeAllListeners("youtube:upload-progress"),
};

contextBridge.exposeInMainWorld("sourceApp", api);
